server:
  error:
  include-message: always
  include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/registration
    username: student
    password: student
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true



